//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInfo
    {
        public int vid { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public Nullable<int> year { get; set; }
        public string imgpath { get; set; }
        public string videopath { get; set; }
        public string description { get; set; }
    }
}
