//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleColorInfo
    {
        public int id { get; set; }
        public int vid { get; set; }
        public string color { get; set; }
        public string hexvalue { get; set; }
    }
}
